apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversaotemperatura
  template: 
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
        - name: conversaotemperatura
          image: dhelly/conversao-temperatura:v1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-conversaotemperatura
spec:
  selector:
    app: conversaotemperatura
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: NodePort
